name: EKS Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      confirm_destroy:
        description: "Type 'yes' to confirm destroy"
        required: false
        default: "no"

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: terraform destroy -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy' && github.event.inputs.confirm_destroy == 'yes'
        run: terraform destroy -auto-approve
